name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - { host: ubuntu-latest, target: linux/amd64 }
          - { host: windows-latest, target: windows/amd64 }
          - { host: macos-latest, target: darwin/amd64 }
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go on ${{ matrix.os.host }}
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'


    - name: Setup  ${{ matrix.os.host }}
      run: go build -v ./...

    - name: Test ${{ matrix.os.host }}
      run: go test -v ./...
